#!/bin/sh
xrandr --nograb --output LVDS1 --auto --output VGA1 --auto --above LVDS1
#xrandr --nograb --output LVDS1 --mode 1366x768 --output VGA1 --mode 1920x1200 --fbmm 518x463 --above LVDS1
#xrandr --nograb --output LVDS1 --mode 1366x768 --output HDMI1 --mode 1920x1200 --fbmm 518x463 --above LVDS1
[ `pgrep -c -f /usr/local/bin/statusbar.sh` -eq 0 ] && statusbar.sh &
syndaemon -i 0.5 -t -d
dwm
